### ISSUE TITLE
Sharding And Canvas Issue

### ISSUE THREAD

**Issue by Dameexe1337** [Uo1428/ALL-IN-ONE-Discord-Bot-#18]
node:internal/modules/cjs/loader:1275
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '\\?\C:\Users\damea\OneDrive\Desktop\ALL-IN-ONE-Discord-Bot--main\node_modules\canvas\build\Release\canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 111. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1275:18)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (C:\Users\damea\OneDrive\Desktop\ALL-IN-ONE-Discord-Bot--main\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12) {
  code: 'ERR_DLOPEN_FAILED'
}
C:\Users\damea\OneDrive\Desktop\ALL-IN-ONE-Discord-Bot--main\node_modules\discord.js\src\sharding\Shard.js:171
        reject(new DiscordjsError(ErrorCodes.ShardingReadyDied, this.id));
               ^

Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.
    at Shard.onDeath (C:\Users\damea\OneDrive\Desktop\ALL-IN-ONE-Discord-Bot--main\node_modules\discord.js\src\sharding\Shard.js:171:16)
    at Object.onceWrapper (node:events:628:26)
    at Shard.emit (node:events:525:35)
    at Shard._handleExit (C:\Users\damea\OneDrive\Desktop\ALL-IN-ONE-Discord-Bot--main\node_modules\discord.js\src\sharding\Shard.js:421:10)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  code: 'ShardingReadyDied'
}

C:\Users\damea\OneDrive\Desktop\ALL-IN-ONE-Discord-Bot--main>

**Comment by Uo1428** [comment]
update node version

**Comment by Dameexe1337** [comment]
> update node version

what version can you send link?

**Comment by Uo1428** [comment]
i updated code use it
